#%RAML 0.8

title: GitHub Game API
baseUri: http://ghgame.mikaelec.com/api/{version}
version: v1

/games:
    post:
        body:
            application/json:
                schema: |
                    { "$schema": "http://json-schema.org/schema",
                        "type": "object",
                        "properties": {
                            "repoURL":  { "type": "string" }
                        },
                        "required": [ "repoURL" ]
                    }
        responses:
            200:
                body:
                    application/json:
                        schema: |
                            {
                                "$schema": "http://json-schema.org/schema",
                                "type": "object",
                                "properties": {
                                    "gameId": { "type": "string" },
                                    "playerId": { "type": "string" }
                                },
                                "required": [ "gameId", "playerId" ]
                            }
    /{gameId}:
        get:
            responses:
                200:
                    body:
                        application/json:
                            schema: |
                                { "$schema": "http://json-schema.org/schema",
                                    "type": "object",
                                    "properties": {
                                        "guessedCommits": { "type": "integer" },
                                        "playingTo": { "type": "integer" }
                                    },
                                    "required": [ "scores", "guessedCommits", "playingTo" ]
                                }

        /commit:
            get:
                responses:
                    200:
                        body:
                            application/json:
                                schema: |
                                    { "$schema": "http://json-schema.org/schema",
                                        "type": "object",
                                        "description": "A new player",
                                        "properties": {
                                            "message":  { "type": "string" },
                                            "rating": { "type": "number" }
                                        },
                                        "required": [ "message", "rating" ]
                                    }

            /guesses:
                get:
                    responses:
                        200:
                            body:
                                application/json:
                                    schema: |
                                        {
                                            "$schema": "http://json-schema.org/schema",
                                            "type": "array",
                                            "items": [
                                                {
                                                    "type": "object",
                                                    "properties": {
                                                        "playerId": { "type": "string" },
                                                        "committerGuess": { "type": "string" },
                                                        "correct": { "type": "boolean" }
                                                    },
                                                    "required": [ "playerId" ]
                                                }
                                            ]
                                        }

                /{playerId}:
                    get:
                        responses:
                            200:
                                body:
                                    application/json:
                                        schema: |
                                            { "$schema": "http://json-schema.org/schema",
                                                "type": "object",
                                                "properties": {
                                                    "committerGuess": { "type": "string" },
                                                    "correct": { "type": "boolean" }
                                                },
                                                "required": [ "playerId" ]
                                            }


        /players:
            post:
                body:
                    application/json:
                        schema: |
                            { "$schema": "http://json-schema.org/schema",
                                "type": "object",
                                "description": "A new player",
                                "properties": {
                                "playerName":  { "type": "string" }
                                },
                                "required": [ "playerName" ]
                            }
                responses:
                    200:
                        body:
                            application/json:
                                schema: |
                                    { "$schema": "http://json-schema.org/schema",
                                        "type": "object",
                                        "properties": {
                                            "playerId":  { "type": "string" }
                                        },
                                        "required": [ "playerId" ]
                                    }
                            
            /{playerId}:
                delete:
                    description: Kick a player
